/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#006fa8',
        'on-primary-container': '#a3faef',
        'surface-dim': '#d2d9f4',
        'on-surface-variant': '#3e4947',
        'secondary-fixed-dim': '#ffb95f',
        'on-surface': '#131b2e',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        outline: '#6e7977',
        tertiary: '#005683',
        'on-secondary-fixed-variant': '#653e00',
        'secondary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#93ccff',
        'on-error': '#ffffff',
        'on-primary-fixed': '#00201d',
        background: '#faf8ff',
        surface: '#faf8ff',
        'on-tertiary-container': '#dbecff',
        'on-tertiary-fixed': '#001d31',
        'primary-fixed': '#9cf2e8',
        'surface-container-low': '#f2f3ff',
        'secondary-container': '#fea619',
        secondary: '#855300',
        'surface-bright': '#faf8ff',
        'on-tertiary-fixed-variant': '#004b73',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'on-secondary-container': '#684000',
        'primary-fixed-dim': '#80d5cb',
        'outline-variant': '#bdc9c6',
        'on-background': '#131b2e',
        'on-error-container': '#93000a',
        'surface-tint': '#006a63',
        'primary-container': '#0f766e',
        'tertiary-fixed': '#cce5ff',
        'on-secondary': '#ffffff',
        'surface-variant': '#dae2fd',
        'surface-container-high': '#e2e7ff',
        'inverse-primary': '#80d5cb',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eef0ff',
        'on-secondary-fixed': '#2a1700',
        'surface-container': '#eaedff',
        'on-primary-fixed-variant': '#00504a',
        'surface-container-highest': '#dae2fd',
        'inverse-surface': '#283044',
        primary: '#005c55',
      },
      spacing: {
        'space-3xl': '3rem',
        'gutter-mobile': '0.75rem',
        'space-md': '0.75rem',
        'space-2xl': '2rem',
        margin: '1.25rem',
        'space-xl': '1.5rem',
        'margin-desktop': '2rem',
        'space-lg': '1rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
        gutter: '1rem',
        'space-2xs': '0.125rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        header: '0 1px 8px rgba(0,0,0,0.04)',
        tabbar: '0 -2px 12px rgba(0,0,0,0.05)',
      },
    },
  },
  plugins: [],
}
